Update : Menambahkan Role Model,Table,Middleware
PPLK-ITERA/PPLK-ITERA-2024 pull request #14
Opened 2024-07-03 05:04 UTC by Xysaa

2024-07-03 06:47 UTC, Gatzmoz requested changes
Buat function untuk store isFirstTimenya supaya jadi false ketika ganti password pertama kali

2024-07-04 04:19 UTC, Gatzmoz approved these changes

2024-07-04 04:46 UTC, Gatzmoz commented on app/Http/Middleware/RoleMiddleware.php
> +        foreach ($roles as $role) {
ini $roles nya darimana ya? bisa tolong dijelaskan sedikit saja

2024-07-04 04:47 UTC, Gatzmoz requested changes
Penjelasan Sedikit

2024-07-04 04:47 UTC, Gatzmoz commented on app/Http/Middleware/RoleMiddleware.php
> +        foreach ($roles as $role) {
atau $roles itu isinya $roles = [rolenya] ?

2024-07-04 05:34 UTC, merged

2024-07-04 06:26 UTC, Xysaa commented on app/Http/Middleware/RoleMiddleware.php
> +        foreach ($roles as $role) {
kalau dari refrensi kemaren dia nyimpen dari routes nya bang, misalnya
 
Route::middleware(['role:admin'])->group(function () {
    Route::get('/admin-dashboard', [AdminController::class, 'adminDashboard'])->name('admin.dashboard');
});

jadi $roles itu isinya admin, kalau ditambah admin,mahasiswa,dapmen berarti isinya bakal ketiga role tersebut yang bisa akses route nya