Feat: menambahkan ViewCount dan OrderBy
PPLK-ITERA/PPLK-ITERA-2024 pull request #5
Opened 2024-07-02 09:34 UTC by dito122140153

2024-07-03 07:17 UTC, Gatzmoz requested changes
Buat function ketika user nekan tombol follow sama unfollow

2024-07-03 07:17 UTC, Gatzmoz commented on app/Http/Controllers/UserController.php
> +         ->makeHidden(['id', 'email', 'password', 'role', 'photo_profile_url', 'linkedin_url', 'instagram_url', 'pilar', 'view_count', 'created_at', 'updated_at']); // Hide unwanted columns
Bisa disederhanakan dengan select di awal User::select('name', 'nim')

2024-07-03 08:46 UTC, dito122140153 commented on app/Http/Controllers/UserController.php
> +         ->makeHidden(['id', 'email', 'password', 'role', 'photo_profile_url', 'linkedin_url', 'instagram_url', 'pilar', 'view_count', 'created_at', 'updated_at']); // Hide unwanted columns
done bang

2024-07-04 05:14 UTC, Gatzmoz approved these changes

2024-07-04 05:14 UTC, merged